name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'New Branch'
        run: |
          pwd
          git --no-pager branch
          git --no-pager tag

          git checkout -b release-0.0.1
          git push origin release-0.0.1


